import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const downloadAmortizationPDF = ({
  loanAmount,
  interestRate,
  loanTenure,
  emi,
  totalInterest,
  totalPayment,
  schedule,
}) => {

  const doc = new jsPDF();

  // ==========================
  // Header
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("LoanWise", 14, 20);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Smart Loan Decisions Made Simple", 14, 28);

  doc.setDrawColor(30, 64, 175);
  doc.line(14, 33, 196, 33);

  // ==========================
  // Report Title
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Loan Amortization Report", 14, 43);

  // ==========================
  // Loan Summary
  // ==========================

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Loan Summary", 14, 55);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  const summary = [
    ["Loan Amount", `₹ ${Number(loanAmount).toLocaleString("en-IN")}`],
    ["Interest Rate", `${interestRate}%`],
    ["Loan Tenure", `${loanTenure} Years`],
    ["Monthly EMI", `₹ ${Number(emi).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`],
    ["Total Interest", `₹ ${Number(totalInterest).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`],
    ["Total Payment", `₹ ${Number(totalPayment).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`],
    ["Generated On", new Date().toLocaleString()],
  ];

  autoTable(doc, {
    startY: 60,
    body: summary,
    theme: "grid",
    styles: {
      fontSize: 10,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 60 },
    },
  });

  // ==========================
  // Monthly Schedule
  // ==========================

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,

    head: [[
      "Month",
      "EMI",
      "Principal",
      "Interest",
      "Balance"
    ]],

    body: schedule.map(item => [
      item.month,
      Number(item.emi).toLocaleString("en-IN", {
        maximumFractionDigits: 2,
      }),
      Number(item.principal).toLocaleString("en-IN", {
        maximumFractionDigits: 2,
      }),
      Number(item.interest).toLocaleString("en-IN", {
        maximumFractionDigits: 2,
      }),
      Number(item.balance).toLocaleString("en-IN", {
        maximumFractionDigits: 2,
      }),
    ]),

    theme: "striped",

    headStyles: {
      fillColor: [37, 99, 235],
      textColor: 255,
      halign: "center",
    },

    styles: {
      fontSize: 9,
      cellPadding: 2,
    },

    alternateRowStyles: {
      fillColor: [245, 247, 250],
    },

    didDrawPage: function () {

      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height
        ? pageSize.height
        : pageSize.getHeight();

      doc.setFontSize(9);

      doc.text(
        `Generated by LoanWise | Page ${doc.getCurrentPageInfo().pageNumber}`,
        14,
        pageHeight - 10
      );

    },

  });

  doc.save("LoanWise_Amortization_Report.pdf");

};